name: TerraForma
main: fat.TerraForma.TerraForma
version: 0.1
softdepend: [Vault]
description: >
             A Terrain tool plugin.
commands:
    tf:
        description: Adjust settings for TerraForma
        usage:
    